### ISSUE TITLE
Could not pass event FactionChatPlayerChatEvent to FactionChat v1.10.0

### ISSUE THREAD

**Issue by L4BORG** [James137137/FactionChat#30]
```
[06:02:38 ERROR]: Could not pass event FactionChatPlayerChatEvent to FactionChat v1.10.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
        at nz.co.lolnet.james137137.FactionChat.FactionChatListener.onChat(FactionChatListener.java:140) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChatListener.onPlayerChat(FactionChatListener.java:121) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChatListener$1.execute(FactionChatListener.java:58) [FactionChat.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1116) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1031) [patched.jar:git-TacoSpigot-"65fd35f"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched.jar:git-TacoSpigot-"65fd35f"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4454) ~[?:1.8.0_111]
        at com.gmail.nossr50.util.player.UserManager.getPlayer(UserManager.java:94) ~[?:?]
        at com.gmail.nossr50.util.player.UserManager.getOfflinePlayer(UserManager.java:83) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.API.McMMOAPI.onPlayerFactionChat(McMMOAPI.java:30) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor475.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
        ... 19 more
```

Latest TacoSpigot 1.8.8, latest McMMo for 1.8, latest MassiveCraft Factions.

**Comment by James137137** [comment]
could you test it on 1.10.1?

**Comment by James137137** [comment]
what version of McMMO are you using?

**Comment by L4BORG** [comment]
https://github.com/mcMMO-Dev/mcMMO/commit/6a0529f02de3d798fa861a5b2302ac80bf3241f3

**Comment by L4BORG** [comment]
We'll try latest build today.

**Comment by James137137** [comment]
and I'll update mcMMO

**Comment by James137137** [comment]
ok you are using 1.5.04-SNAPSHOT

when I'm using.... 1.5.07-SNAPSHOT (1.5.06+)

It should work but try updating
