### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by PyvesB** [James137137/FactionChat#33]
Hello James137137,

We are getting the following error with FactionChat  on startup:

```
[08:52:05 INFO]: [FactionChat] Enabling FactionChat v1.10.4
[08:52:05 INFO]: FactionChat: Version: 1.10.4 Enabling
[08:52:05 ERROR]: null
java.lang.NullPointerException
        at nz.co.lolnet.james137137.FactionChat.PrefixAndSuffix.VaultChat.setupChat(VaultChat.java:37) ~[FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.PrefixAndSuffix.VaultChat.init(VaultChat.java:22) ~[FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.API.FactionChatAPI.setupPreSuffixPlugin(FactionChatAPI.java:78) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.API.FactionChatAPI.setupAPI(FactionChatAPI.java:33) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChat.onEnable(FactionChat.java:76) [FactionChat.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [craftbukkit.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[08:52:05 INFO]: [FactionChat] using Factions API of: nz.co.lolnet.james137137.FactionChat.FactionsAPI.FactionsAPI_2_10_0
```

The server setup is the following: Spigot 1.11.2 compiled last Thursday, Vault 1.5.6, Factions and MassiveCore 2.10.0 and FactionChat 1.10.4.

This exception does not occur when reverting back to FactionChat  1.10.2.

Cheers,

Pyves

**Comment by James137137** [comment]
Thanks for the report. on to fixing it now

**Comment by James137137** [comment]
should be fixed. test build jar is https://jenkins.lolnet.co.nz/job/FactionChat/151

**Comment by PyvesB** [comment]
Thank you for your answer. Unfortunately, I still seem to be having the same issue:

```
[09:33:43 INFO]: [FactionChat] Enabling FactionChat v1.10.5-SNAPSHOT
[09:33:43 INFO]: FactionChat: Version: 1.10.5-SNAPSHOT Enabling
[09:33:43 ERROR]: null
java.lang.NullPointerException: null
        at nz.co.lolnet.james137137.FactionChat.PrefixAndSuffix.VaultChat.setupChat(VaultChat.java:45) ~[FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.PrefixAndSuffix.VaultChat.init(VaultChat.java:26) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.API.FactionChatAPI.setupPreSuffixPlugin(FactionChatAPI.java:79) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.API.FactionChatAPI.setupAPI(FactionChatAPI.java:34) [FactionChat.jar:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChat.onEnable(FactionChat.java:76) [FactionChat.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:326) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:743) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:643) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:629) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [craftbukkit.jar:git-Spigot-6629162-cda27c9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[09:33:43 INFO]: [FactionChat] using Factions API of: nz.co.lolnet.james137137.FactionChat.FactionsAPI.FactionsAPI_2_10_0
[09:33:43 INFO]: FactionChat: Version: 1.10.5-SNAPSHOT Enabled.
```

**Comment by James137137** [comment]
Thanks for the update..... Yeah I'm starting to wish I didn't support vaults :-p

**Comment by James137137** [comment]
Pushed an untested patch (see  https://jenkins.lolnet.co.nz/job/FactionChat/)

I'll be testing and fixing this (and the chat format) in the weekend

**Comment by PyvesB** [comment]
Just tested the latest build now. No exceptions on startup this time! ;-)

**Comment by James137137** [comment]
Cool I'll close this now.
