### ISSUE TITLE
Faction Chat does not work with 1.13 Factions3 Massivecraft fork

### ISSUE THREAD

**Issue by 00Nave198** [James137137/FactionChat#40]
I cant get this plugin to work correctly with the factions3 fork.  Factions3 is forked from the Massivecraft version, but I do not know how much is changed.  When I attempt to use Factionchat v1.10.8, Factions3 v3.1.5, and paper-568 server it gave this stacktrace every time I said something in chat after switching to a chat added by factionchat.  My message was then printed in public chat.  When switched back to public the stacktrace would not appear.
`[14:36:01 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fc' in plugin FactionChat v1.10.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[patched_1.13.2.jar:git-Paper-568]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-568]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1782) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-568]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1011) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-568]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-568]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: com.massivecraft.factions.entity.MPlayer.getRole()Lcom/massivecraft/factions/Rel;
        at nz.co.lolnet.james137137.FactionChat.FactionsAPI.FactionsAPI_2_12_0.getPlayerRank(FactionsAPI_2_12_0.java:92) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.FactionsAPI.PreFactionsAPI.getPlayerRank(PreFactionsAPI.java:79) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.API.FactionChatAPI.getPlayerRank(FactionChatAPI.java:107) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.ChatMode.setChatMode(ChatMode.java:234) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChat.CommandFC(FactionChat.java:546) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChat.onCommand(FactionChat.java:183) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-568]
        ... 15 more`
Would you be able to ad support for Factions3?
Factions3: https://www.spigotmc.org/resources/factions3-for-1-13.63602/

**Comment by XGNXLency** [comment]
I'm having the same problem.

**Comment by XGNXLency** [comment]
A month and still no update. Jesus.

**Comment by 00Nave198** [comment]
Honestly I doubt this will be updated, this plugin does not look like its in active development.  The plugin does not claim support for the Factions3 port either.  I can't really blame the author for not wanting to update the plugin.  There are other solutions available depending on version.

**Comment by XGNXLency** [comment]
It's okay. I quit Minecraft a couple of days ago. The author of Factions3 is a massive Jew and and a jackass. Don't even bother supporting it.
