### ISSUE TITLE
error on fchat reload on console

### ISSUE THREAD

**Issue by madtomic** [James137137/FactionChat#9]
>fchat reload
[14:59:07 WARN]: Unexpected exception while parsing console command "fchat reloa
d"
org.bukkit.command.CommandException: Unhandled exception executing command 'fcha
t' in plugin FactionChat v1.9.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) ~[spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServe
r.java:646) ~[spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchServerCommand(Craf
tServer.java:632) [spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(DedicatedServer.java:
405) [spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:3
69) [spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:6
51) [spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java
:554) [spigot-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
        at nz.co.lolnet.james137137.FactionChat.FactionsAPI.FactionsAPI_2_7_0.ge
tFactionName(FactionsAPI_2_7_0.java:23) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChat.CommandFC(FactionCha
t.java:613) ~[?:?]
        at nz.co.lolnet.james137137.FactionChat.FactionChat.onCommand(FactionCha
t.java:306) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got-1.8.3.jar:git-Spigot-0b997a9-30d751b]
        ... 8 more

**Comment by James137137** [comment]
yeah... reloading FactionChat via console hasn't always worked perfectly...

**Comment by James137137** [comment]
Fixed as of 78ec2c232e5e809355432beeb7cd25f7313596e7

**Comment by James137137** [comment]
Feel free to reopen if not resolved

**Comment by James137137** [comment]
btw latest version is: http://anderson.lolnet.co.nz:8081/job/FactionChat/
